# Numpy

In [1]:
import numpy as np

In [2]:
mi_lista = [1, 2, 3]

In [3]:
np.array(mi_lista)

array([1, 2, 3])

In [4]:
matrix = [ [1,2,3] , [4,5,6] , [7,8,9] ];

In [5]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros( (3,3) )

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones( (3,3) )

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random

rand: genera entre [0, 1)

In [15]:
np.random.rand(2)

array([0.32851486, 0.12790876])

In [16]:
np.random.rand(5,5)

array([[0.54087439, 0.06175264, 0.59641398, 0.20734281, 0.95915456],
       [0.25137802, 0.57241402, 0.99102494, 0.33613543, 0.06199658],
       [0.76897325, 0.56911987, 0.18550821, 0.53653479, 0.82569906],
       [0.61760156, 0.30320918, 0.13371558, 0.57552922, 0.29685323],
       [0.24642151, 0.89015867, 0.93728917, 0.51754188, 0.95151218]])

randn: retorna los valores desde un distribucion normal estandar

In [17]:
np.random.randn(2)

array([0.83587905, 0.09349848])

In [18]:
np.random.rand(5,5)

array([[0.7982954 , 0.59644824, 0.72838115, 0.1576935 , 0.77246303],
       [0.20561768, 0.31473003, 0.23640383, 0.8375139 , 0.45127861],
       [0.38333056, 0.34157117, 0.1197453 , 0.70357607, 0.95070338],
       [0.72657231, 0.80912254, 0.33461181, 0.1034964 , 0.77126311],
       [0.99901431, 0.71088963, 0.52382124, 0.69473358, 0.84896436]])

randint: generar valores aleatorios enteros entre un limite inferior y uno superior

In [19]:
np.random.randint(1, 100)

40

In [20]:
np.random.randint(1, 100, 10)

array([23, 29, 30,  3, 69, 87, 77,  2, 14, 55])

# Metodos

In [21]:
array([1 2 3 4 5 .. 24])

SyntaxError: invalid syntax (<ipython-input-21-41c51824012b>, line 1)

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

reshape

In [64]:
arr.reshape(5,5)

array([[  0, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [100,  21,  22,  23,  24]])

In [25]:
arrrand = np.random.randint(0, 50, 10)

In [26]:
arrrand

array([44, 11, 44,  6, 10, 21, 22, 26,  1, 20])

In [27]:
arrrand.min()

1

In [28]:
arrrand.max()

44

In [29]:
arr.shape

(25,)

In [30]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [31]:
arr.reshape(1, 25).shape

(1, 25)

In [32]:
arr.dtype

dtype('int32')

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr[8]

8

In [35]:
arr[1:5]

array([1, 2, 3, 4])

In [36]:
arr[18:25]

array([18, 19, 20, 21, 22, 23, 24])

In [37]:
arr[18:]

array([18, 19, 20, 21, 22, 23, 24])

In [38]:
arr[20] = 100

In [39]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 100,  21,  22,  23,  24])

In [40]:
arr[1:5] = 100

In [41]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 100,  21,  22,  23,  24])

In [42]:
matriz1 = np.array( ([5, 10, 15], [20, 12, 17], [54,56,9]) )

In [43]:
matriz1

array([[ 5, 10, 15],
       [20, 12, 17],
       [54, 56,  9]])

In [44]:
matriz1[1]

array([20, 12, 17])

In [45]:
matriz1[1][2]

17

# Operaciones

In [46]:
vector = np.arange(0, 10)

In [47]:
vector + vector

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
vector*vector

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [50]:
vector - vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
vector**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [52]:
np.sqrt(vector)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [53]:
np.exp(vector)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [54]:
np.max(vector)

9