In [1]:
import numpy as np

In [2]:
ar=np.random.randint(0,100,15)
ar

array([81, 16, 47, 70,  7, 33, 13,  2,  2, 31,  2, 50, 93, 38, 35])

In [3]:
np.delete(ar,[range(3)])

array([70,  7, 33, 13,  2,  2, 31,  2, 50, 93, 38, 35])

In [4]:
lista=ar.tolist()
lista

[81, 16, 47, 70, 7, 33, 13, 2, 2, 31, 2, 50, 93, 38, 35]

In [5]:
mat=ar.reshape(5,3)
mat

array([[81, 16, 47],
       [70,  7, 33],
       [13,  2,  2],
       [31,  2, 50],
       [93, 38, 35]])

In [6]:
mat_sorted_0=mat.copy()
mat_sorted_0.sort(axis=0)
mat_sorted_0

array([[13,  2,  2],
       [31,  2, 33],
       [70,  7, 35],
       [81, 16, 47],
       [93, 38, 50]])

In [7]:
mat_sorted_1=mat.copy()
mat_sorted_1.sort()
mat_sorted_1

array([[16, 47, 81],
       [ 7, 33, 70],
       [ 2,  2, 13],
       [ 2, 31, 50],
       [35, 38, 93]])

In [8]:
mat.size

15

In [11]:
lista.index(47)

2

In [12]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}

In [13]:
list(x.keys())

['Bill Gates', 'Christopher Brooks']

In [20]:
list(x.values())

['billg@microsoft.com', 'brooksch@umich.edu']

In [22]:
x.items()

dict_items([('Bill Gates', 'billg@microsoft.com'), ('Christopher Brooks', 'brooksch@umich.edu')])